services:
  postgres:
    image: postgres:latest
    container_name: 'to-do'
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=to-do
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
